### ISSUE TITLE
Scroll 

### ISSUE THREAD

**Issue by wondimagagnzewudu** [Svetloslav15/react-sidebar-ui#11]
I want to add the Schroll menu

**Comment by VisheshNucleusTeq** [comment]
yes there is no scroll due to which whole menu is not visible

**Comment by wondimagagnzewudu** [comment]
thanks for your time I tried to create my own css

**Comment by Svetloslav15** [comment]
Scroll will be available in v2 of the library which will be released soon. @wondimagagnzewudu  @VisheshNucleusTeq
