### ISSUE TITLE
I tried the same as in the docs, but the styling is not applying to my component. 

### ISSUE THREAD

**Issue by bonniesimon** [Svetloslav15/react-sidebar-ui#8]
Yes I did import the css file as given in the docs.

**Comment by CoderUIBg** [comment]
Did you import font-awesome?

**Comment by Svetloslav15** [comment]
Did you import font-awesome in your project?

**Comment by Svetloslav15** [comment]
import the style into your index.html file and everything will work correctly. 
    <link rel="stylesheet" href="https://unpkg.com/react-sidebar-ui@1.1.8/dist/index.css" type="text/css">

**Comment by Svetloslav15** [comment]
<link rel="stylesheet" href="https://unpkg.com/react-sidebar-ui@1.1.8/dist/index.css" type="text/css">

**Comment by Svetloslav15** [comment]
The bug is fixed in version 1.1.8
You should:
1. Import **https://unpkg.com/react-sidebar-ui@1.1.8/dist/index.css** into your index.html file
2. In order to use icons, you should import Font-Awesome
